In [69]:
import pandas as pd

In [ ]:
#To read the csv file, we can use the read_csv() function from the pandas library.
df=pd.read_csv("weather.csv")
print(df)

         date  temperature  humidity  wind_speed
0  2023-10-01         25.5        60          15
1  2023-10-02         26.0        65          10
2  2023-10-03         24.8        70          12
3  2023-10-04         27.2        55          20
4  2023-10-05         23.5        75           8
5  2023-10-06         22.0        80           5

In [71]:
#To get the first 2 rows of the dataframe, we can use the head() function.
print(df.head(2))

         date  temperature  humidity  wind_speed
0  2023-10-01         25.5        60          15
1  2023-10-02         26.0        65          10

In [72]:
#To get the last few rows
print(df.tail(2))

         date  temperature  humidity  wind_speed
4  2023-10-05         23.5        75           8
5  2023-10-06         22.0        80           5

In [73]:
#slicing
df[2:5]

         date  temperature  humidity  wind_speed
2  2023-10-03         24.8        70          12
3  2023-10-04         27.2        55          20
4  2023-10-05         23.5        75           8

In [74]:
#To print all the columns
df.columns

Index(['date', 'temperature', 'humidity', 'wind_speed'], dtype='object')

In [75]:
#Specific column
df['temperature']

0    25.5
1    26.0
2    24.8
3    27.2
4    23.5
5    22.0
Name: temperature, dtype: float64

In [76]:
#Specific columns
df[['temperature','date']]

   temperature        date
0         25.5  2023-10-01
1         26.0  2023-10-02
2         24.8  2023-10-03
3         27.2  2023-10-04
4         23.5  2023-10-05
5         22.0  2023-10-06

In [77]:
#type of data in our csv file
type(df['date'])

pandas.core.series.Series

In [78]:
#to print the statistics of the given data
df.describe()

       temperature   humidity  wind_speed
count     6.000000   6.000000    6.000000
mean     24.833333  67.500000   11.666667
std       1.855442   9.354143    5.316641
min      22.000000  55.000000    5.000000
25%      23.825000  61.250000    8.500000
50%      25.150000  67.500000   11.000000
75%      25.875000  73.750000   14.250000
max      27.200000  80.000000   20.000000

Conditional Query

In [79]:
#1
df[df.temperature>=24]

         date  temperature  humidity  wind_speed
0  2023-10-01         25.5        60          15
1  2023-10-02         26.0        65          10
2  2023-10-03         24.8        70          12
3  2023-10-04         27.2        55          20

In [80]:
#2.1
df[df.temperature==df.temperature.max()]

         date  temperature  humidity  wind_speed
3  2023-10-04         27.2        55          20

In [81]:
#2.2
df[df.temperature==df["temperature"].max()]

         date  temperature  humidity  wind_speed
3  2023-10-04         27.2        55          20

In [82]:
#3
df[['date','temperature']][df.temperature==df['temperature'].max()]

         date  temperature
3  2023-10-04         27.2

In [83]:
#to get the data type of each column
df.dtypes

date            object
temperature    float64
humidity         int64
wind_speed       int64
dtype: object

In [84]:
#to specify the index of the dataframe
print(df.index)

RangeIndex(start=0, stop=6, step=1)

In [ ]:
df.set_index('temperature', inplace=True)
df.loc[24.8]  # Works if 24.8 is in the 'temperature' column

In [86]:
#to reset the index of the dataframe
df.reset_index(inplace=True)
print(df)

   temperature        date  humidity  wind_speed
0         25.5  2023-10-01        60          15
1         26.0  2023-10-02        65          10
2         24.8  2023-10-03        70          12
3         27.2  2023-10-04        55          20
4         23.5  2023-10-05        75           8
5         22.0  2023-10-06        80           5

Modifying the data

1.Inserting new column

In [15]:
import pandas as pd
data={
    "Name":["Priyanka","Shruti","Ayush","Himanshu","Tripti","Angel"],
    "age":[20,21,24,27,28,29],
    "Salary(in USD)":[20,40,23,54,32,45]
}
df=pd.DataFrame(data)

In [16]:
#1
df["Department"]=["AI","CS","IT","DS","AI","IT"]
df

       Name  age  Salary(in USD) Department
0  Priyanka   20              20         AI
1    Shruti   21              40         CS
2     Ayush   24              23         IT
3  Himanshu   27              54         DS
4    Tripti   28              32         AI
5     Angel   29              45         IT

In [17]:
#2 Using insert ----df.insert(index,column_name,value)
df.insert(0,"E_ID",[1,2,3,4,5,6])
df

   E_ID      Name  age  Salary(in USD) Department
0     1  Priyanka   20              20         AI
1     2    Shruti   21              40         CS
2     3     Ayush   24              23         IT
3     4  Himanshu   27              54         DS
4     5    Tripti   28              32         AI
5     6     Angel   29              45         IT

2.Updating the column value---loc[row index,column name]=updated value

In [18]:
df.loc[0,"Name"]="Priyanshi"
df

   E_ID       Name  age  Salary(in USD) Department
0     1  Priyanshi   20              20         AI
1     2     Shruti   21              40         CS
2     3      Ayush   24              23         IT
3     4   Himanshu   27              54         DS
4     5     Tripti   28              32         AI
5     6      Angel   29              45         IT

In [19]:
df.loc[[0,1,2,3,4,5],"E_ID"]=[101,102,103,104,105,106]
df

   E_ID       Name  age  Salary(in USD) Department
0   101  Priyanshi   20              20         AI
1   102     Shruti   21              40         CS
2   103      Ayush   24              23         IT
3   104   Himanshu   27              54         DS
4   105     Tripti   28              32         AI
5   106      Angel   29              45         IT

In [22]:
df["Salary(in USD)"]=df["Salary(in USD)"]*1.05
df

   E_ID       Name  age  Salary(in USD) Department
0   101  Priyanshi   20           2.100         AI
1   102     Shruti   21           4.200         CS
2   103      Ayush   24           2.415         IT
3   104   Himanshu   27           5.670         DS
4   105     Tripti   28           3.360         AI
5   106      Angel   29           4.725         IT

3.Removing  a column---drop(columns=["column name",column name2,....],inplace=True)

In [ ]:
df.drop(columns=["E_ID"],inplace=True)
df

        Name  age  Salary(in USD) Department
0  Priyanshi   20           2.100         AI
1     Shruti   21           4.200         CS
2      Ayush   24           2.415         IT
3   Himanshu   27           5.670         DS
4     Tripti   28           3.360         AI
5      Angel   29           4.725         IT